"""third phase

Revision ID: 839c0969eb28
Revises: 32348278033f
Create Date: 2024-12-02 17:23:24.028138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839c0969eb28'
down_revision: Union[str, None] = '32348278033f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfs', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pdfs', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('pdfs', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pdfs', 'extracted_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfs', 'extracted_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('pdfs', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pdfs', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('pdfs', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
